[[track]]
name = "Gamecube Music"
url = "https://www.youtube.com/watch?v=tDQHmxN6QFc"

[[track]]
name = "Gran Turismo"
url = "https://www.youtube.com/watch?v=QXAoknKbgBc"

[[track]]
name = "PS1 Music - 1"
url = "https://www.youtube.com/watch?v=5wDpGrf-fCk"

[[track]]
name = "Delfino Relax"
url = "https://www.youtube.com/watch?v=15qNTBVx7_M"
